name: Build and deploy APK

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch master branch
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build Release APK
        run: ./gradlew clean assembleRelease

      - name: Rename APK file
        run: cd app/build/outputs/apk/release && mv app-release-unsigned.apk ChuckNorrisQuotes.apk

      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: lb-tasks-apk
          path: 'app/build/outputs/apk/release/ChuckNorrisQuotes.apk'
